export const actionType = {
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOG_OUT: "LOG_OUT",
	GET_ALL_CART: "GET_ALL_CART",
	ADD_TO_CART: "ADD_TO_CART",
	REMOVE_FROM_CART: "REMOVE_FROM_CART",
	CHANGE_TAB: "CHANGE_TAB",
};
