export const actionType = {
	SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
	SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
	SIGN_OUT: "SIGN_OUT",
	GET_ALL_CART: "GET_ALL_CART",
	ADD_TO_CART: "ADD_TO_CART",
	REMOVE_FROM_CART: "REMOVE_FROM_CART",
	CHANGE_TAB: "CHANGE_TAB",
};
