export const CONSTANT = {
	FORMAT_DATE: "DD/MM/YYYY",
	FORMAT_DATE_HOUR: "DD/MM/YYYY HH:mm:ss",
	DEFAULT_PAGE: "1",
	DEFAULT_SIZE: "8",
	DEFAULT_KEYWORD: "",
	DEFAULT_FILTER: "",
	DEFAULT_SORT_PRICE: "",
};
